version: "3"
services:
  frontend:
    container_name: nsbj-front
    build: 
      context: ./front-end-pwa
      dockerfile: Dockerfile.dev
    ports: # nginx 생성 시 포트 제거
      - "3000:3000"
    # volumes: 
      # - /usr/front/node_modules
      # - ./front-end-pwa:/usr/front
    environment: 
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  backend:
    container_name: nsbj-back
    build: 
      context: ./backend/birdmouse
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:8080"
    # depends_on: 
    #   - "frontend"
  
  redis:
    image: redis
    container_name: nsbj-redis
    ports: 
      - "6379:6379"

    # nginx:
  #   restart: always
  #   build: 
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports: 
  #     - "3000:80"

