version: "3"
services:
  frontend:
    container_name: nsbj-front
    build: 
      context: ./front-end-pwa
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # volumes: 
      # - /usr/front/node_modules
      # - ./front-end-pwa:/app
    environment: 
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on: 
      - backend

  backend:
    container_name: nsbj-back
    build: 
      context: ./backend/birdmouse
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.dev
    # restart: on-failure
    ports: 
      - "8080:8080"
  
  redis:
    image: redis
    container_name: nsbj-redis
    ports: 
      - "6379:6379"

  nginx:
    image: nginx
    ports: 
      - "80:80"
      - "443:443"

networks:
  nginx:
    external: true

