FROM node:14.16.1-alpine3.10

WORKDIR /usr/front

COPY ["package.json", "tsconfig.json",".eslintrc.js","alltypes.d.ts", "./"]

RUN yarn install

COPY ./ ./

CMD ["yarn", "start"]
# CMD ["yarn", "dev"]
